//
//  ChuckModel.swift
//  funFacts
//
//  Created by Parker Donat on 7/5/16.
//  Copyright © 2016 Parker Donat. All rights reserved.
//

import GameKit

class Joke: Equatable {
    
    private let kJoke = "Joke"
    
    var text: String
    
    var dictionaryCopy: [String: AnyObject] {
        return [kJoke: text]
    }
    
    init(joke: String) {
        self.text = joke
    }
    
    init?(dictionary: [String: AnyObject]) {
        guard let  jokeDictionary = dictionary[kJoke] as? String else { return nil }
    
        self.text = jokeDictionary
    }
}

func ==(lhs: Joke, rhs: Joke) -> Bool {
    
    return ObjectIdentifier(lhs) == ObjectIdentifier(rhs)
}

struct ChuckModel {
    let chuckJokes = [
        
        "Chuck Norris caught all the Pokémon in one throw with the Pokémon Go app.",
        "A grown adult has 206 bones in their body but when Chuck Norris hits you with a roundhouse kick to the face you'll have about 3,000,000 bones.",
        "That's not an eclipse. It’s the sun hiding from Chuck Norris.",
        "Ghosts sit around the campfire and tell Chuck Norris stories.",
        "They wanted to put Chuck Norris' face on Mount Rushmore but the granite wasn't strong enough for his beard.",
        "Contrary to popular belief, America is not a democracy, it is a Chucktatorship.",
        "Chuck Norris does not get frostbite. Chuck Norris bites frost.",
        "Chuck Norris can spit through bulletproof glass.",
        "Chuck Norris does not sleep; he waits.",
        "When Chuck Norris works out he doesn't get stronger, the machine does.",
        "If you see Chuck Norris crying he will grant you a wish, if your wish is dying.",
        "Chuck Norris wears sunglasses so his eyes won't hurt the sun.",
        "Chuck Norris doesn't breathe air. He holds air hostage.",
        "When Chuck Norris swims in the ocean, the sharks are in a steel cage.",
        "When Chuck Norris turned 18, his parents moved out.",
        "If Chuck Norris was a Spartan in the movie 300, the movie would be called One.",
        "Chuck Norris is currently suing NBC, claiming Law and Order are trademarked names for his left and right legs.",
        "The easiest way to determine Chuck Norris's age is to cut him in half and count the rings.",
        "He who laughs last, laughs best. He who laughs at Chuck Norris, it's definitely his last laugh.",
        "Chuck Norris doesn’t need a weapon. He is one.",
        "There is only one way to determine if Chuck Norris likes you... are you still alive to read this?",
        "Chuck Norris killed Bin Laden before the SEALs got there.",
        "When the mother of Chuck Norris was pregnant she could feel him moving in her stomache. Little did she know, he was perfecting his roundhouse kick.",
        "When he was a kid, Chuck Norris' bedroom walls were filled with photos of Chuck Norris.",
        "When you get a thumbs up from Chuck Norris, you always win.",
        "Why do vultures suddenly appear every time Chuck Norris is near? Just like me, they long to be... close to Chuck.",
        "Chuck Norris doesn't listen to music. Music listens to Chuck Norris.",
        "Usain Bolt broke the 100m record by accident because he was trying to run away from Chuck Norris.",
        "MacGyver can build an airplane out of gum and paper clips. Chuck Norris can kill him and take it.",
        "Chuck Norris doesn't read books. He stares them down until he gets the information he wants.",
        "If you ask Chuck Norris what time it is, he always answers 'Two seconds till'. After you ask 'Two seconds to what?', he roundhouse kicks you in the face.",
        "Since 1940, the year Chuck Norris was born, roundhouse kick related deaths have increased 13,000 percent.",
        "There are no steroids in baseball. Just players Chuck Norris has breathed on.",
        "When Chuck Norris goes to donate blood, he declines the syringe, and instead requests a hand gun and a bucket.",
        "Pluto is actually an orbiting group of British soldiers from the American Revolution who entered space after Chuck Norris gave them a roundhouse kick to the face.",
        "According to the Encyclopedia Brittanica, the Native American 'Trail of Tears' has been redefined as anywhere that Chuck Norris walks.",
        "In an average living room there are 1,242 objects Chuck Norris could use to kill you, including the room itself.",
        "The Chuck Norris military unit was not used in the game Civilization 4, because a single Chuck Norris could defeat the entire combined nations of the world in one turn.",
        "Chuck Norris doesn't shower, he only takes blood baths.",
        "Time waits for no man. Unless that man is Chuck Norris.",
        "Chuck Norris can hit you so hard that he can actually alter your DNA. Decades from now your descendants will occasionally clutch their heads and yell 'What The Hell was That?'.",
        "Chuck Norris is the only human being to display the Heisenberg uncertainty principle... you can never know both exactly where and how quickly he will roundhouse kick you in the face.",
        "Faster than a speeding bullet... more powerful than a locomotive... able to leap tall buildings in a single bound... these are some of Chuck Norris's warm-up exercises.",
        "Chuck Norris is not hung like a horse. Horses are hung like Chuck Norris.",
        "Teenage Mutant Ninja Turtles is based on a true story: Chuck Norris once swallowed a turtle whole, and when he crapped it out, the turtle was six feet tall and had learned karate.",
        "Someone once tried to tell Chuck Norris that roundhouse kicks aren't the best way to kick someone. This has been recorded by historians as the worst mistake anyone has ever made.",
        "Chuck Norris has two speeds: Walk and Kill.",
        "Chuck Norris once shot down a fighter airplane with his finger. By yelling 'Bang!'",
        "The opening scene of the movie 'Saving Private Ryan' is loosely based on games of dodgeball Chuck Norris played in second grade.",
        "Fool me once, shame on you. Fool Chuck Norris once and he will roundhouse kick you in the face.",
        "Chuck Norris originally appeared in the 'Halo' video game, but was removed by Beta Testers because every button caused him to do a roundhouse kick. When asked about this glitch, Norris replied 'That's no glitch.'",
        "If you spell Chuck Norris in Scrabble, you win. Forever.",
        "Someone once videotaped Chuck Norris getting pissed off. It was called Walker: Texas Chain Saw Masacre.",
        "Chuck Norris will attain statehood in 2020. His state flower will be the Magnolia.",
        "A handicapped parking sign does not signify that this spot is for handicapped people. It is actually in fact a warning, that the spot belongs to Chuck Norris and that you will be handicapped if you park there.",
        "Chuck Norris doesn't wash his clothes. He disembowels them.",
        "Chuck Norris doesn't churn butter. He roundhouse kicks the cows and the butter comes straight out.",
        "Police label anyone attacking Chuck Norris as a Code 45-11... a suicide.",
        "Chuck Norris is the only man to ever defeat a brick wall in a game of tennis.",
        "What was going through the minds of all of Chuck Norris' victims before they died? His shoe.",
        "There is no theory of evolution, just a list of creatures Chuck Norris allows to live.",
        "Chuck Norris can win a game of Connect Four in only three moves.",
        "CNN was originally created as the 'Chuck Norris Network' to update Americans with on-the-spot roundhouse kicking in real-time.",
        "Chuck Norris invented Kentucky Fried Chicken's famous secret recipe with eleven herbs and spices. Nobody ever mentions the twelfth ingredient: Fear.",
        "The quickest way to a man's heart is with Chuck Norris' fist.",
        "When Chuck Norris sends in his taxes, he sends blank forms and includes only a picture of himself, crouched and ready to attack. Chuck Norris has not had to pay taxes, ever.",
        "Most people have 23 pairs of chromosomes. Chuck Norris has 72... and they're all poisonous.",
        "The Great Wall of China was originally created to keep Chuck Norris out. It failed miserably.",
        "Crop circles are Chuck Norris' way of telling the world that sometimes corn needs to lie down.",
        "Chuck Norris once roundhouse kicked someone so hard that his foot broke the speed of light, went back in time, and killed Amelia Earhart while she was flying over the Pacific Ocean.",
        "When Chuck Norris calls 1-900 numbers, he doesn't get charged. He holds up the phone and money falls out.",
        "Some people like to eat frogs' legs. Chuck Norris likes to eat lizard legs. Hence, snakes.",
        "There are no races, only countries of people Chuck Norris has beaten to different shades of black and blue.",
        "Chuck Norris can't finish a 'color by numbers' because his markers are filled with the blood of his victims. Unfortunately, all blood is dark red.",
        "Scientists have estimated that the energy given off during the Big Bang is roughly equal to 1CNRhK (Chuck Norris Roundhouse Kick).",
        "Chuck Norris' house has no doors, only walls that he walks through.",
        "How much wood would a woodchuck chuck if a woodchuck could Chuck Norris? All of it.",
        "Chuck Norris doesn't actually write books, the words assemble themselves out of fear.",
        "In honor of Chuck Norris, all McDonald's in Texas have an even larger size than the super-size. When ordering, just ask to be Chucksized.",
        "Chuck Norris can believe it's not butter.",
        "If tapped, a Chuck Norris roundhouse kick could power the country of Australia for 44 minutes.",
        "Chuck Norris can divide by zero.",
        "The grass is always greener on the other side, unless Chuck Norris has been there. In that case the grass is most likely soaked in blood and tears.",
        "Newton's Third Law is wrong: Although it states that for each action, there is an equal and opposite reaction, there is no force equal in reaction to a Chuck Norris roundhouse kick.",
        "Chuck Norris invented his own type of karate. It's called Chuck-Will-Kill.",
        "When an episode of Walker Texas Ranger was aired in France, the French surrendered to Chuck Norris just to be on the safe side.",
        "While urinating, Chuck Norris is easily capable of welding titanium.",
        "When Chuck Norris talks, everybody listens. And dies.",
        "Contrary to popular belief, there is indeed enough Chuck Norris to go around.",
        "Chuck Norris doesn’t shave; he kicks himself in the face.",
        "The only thing that can cut Chuck Norris is Chuck Norris.",
        "Chuck Norris always knows the EXACT location of Carmen SanDiego.",
        "When taking the SAT, write 'Chuck Norris' for every answer. You will score over 8000.",
        "Chuck Norris invented black. In fact, he invented the entire spectrum of visible light. Except pink. Tom Cruise invented pink.",
        "When you're Chuck Norris, anything + anything is equal to 1. One roundhouse kick to the face.",
        "Chuck Norris has the greatest Poker-Face of all time. He won the 1983 World Series of Poker, despite holding only a Joker, a Get out of Jail Free Monopoloy card, a 2 of clubs, 7 of spades and a green #4 card from the game UNO.",
        "Chuck Norris doesn't throw up if he drinks too much. Chuck Norris throws down!",
        "In the beginning there was nothing... then Chuck Norris roundhouse kicked that nothing in the face and said 'Get a job'. That is the story of the universe.",
        "Chuck Norris has 12 moons. One of those moons is the Earth.",
        "Chuck Norris grinds his coffee with his teeth and boils the water with his own rage.",
        "Archeologists unearthed an old english dictionary dating back to the year 1236. It defined 'victim' as 'one who has encountered Chuck Norris'",
        "Chuck Norris ordered a Big Mac at Burger King, and got one.",
        "Chuck Norris and Mr. T walked into a bar. The bar was instantly destroyed, as that level of awesome cannot be contained in one building.",
        "If you Google search 'Chuck Norris getting his ass kicked' you will generate zero results. It just doesn't happen.",
        "Little known medical fact: Chuck Norris invented the Caesarean section when he roundhouse kicked his way out of his monther's womb.",
        "Chuck Norris doesn't bowl strikes, he just knocks down one pin and the other nine faint.",
        "The show Survivor had the original premise of putting people on an island with Chuck Norris. There were no survivors, and nobody is brave enough to go to the island to retrieve the footage.",
        "It takes Chuck Norris 20 minutes to watch 60 Minutes.",
        "You know how they say if you die in your dream then you will die in real life? In actuality, if you dream of death then Chuck Norris will find you and kill you.",
        "Chuck Norris has a deep and abiding respect for human life... unless it gets in his way.",
        "The Bermuda Triangle used to be the Bermuda Square, until Chuck Norris roundhouse kicked one of the corners off.",
        "When Chuck Norris is in a crowded area, he doesn't walk around people. He walks through them.",
        "Chuck Norris once ate an entire bottle of sleeping pills. They made him blink.",
        "James Cameron wanted Chuck Norris to play the Terminator. However, upon reflection, he realized that would have turned his movie into a documentary, so he went with Arnold Schwarzenegger.",
        "Chuck Norris can touch MC Hammer.",
        "Thousands of years ago Chuck Norris came across a bear. It was so terrified that it fled north into the arctic. It was also so terrified that all of its decendents now have white hair.",
        "Chuck Norris played Russian Roulette with a fully loaded gun and won.",
        "Some people wear Superman pajamas. Superman wears Chuck Norris pajamas.",
        "Chuck Norris once worked as a weatherman for the San Diego evening news. Every night he would make the same forecast: Partly cloudy with a 75% chance of Pain.",
        "Simply by pulling on both ends, Chuck Norris can stretch diamonds back into coal.",
        "When Chuck Norris does a pushup, he isn't lifting himself up, he's pushing the Earth down.",
        "Chuck Norris keeps his friends close and his enemies closer. Close enough to drop them with one roundhouse kick to the face.",
        "There is in fact an 'I' in Norris, but there is no 'team'. Not even close.",
        "Scotty in Star Trek often says 'Ye cannot change the laws of physics.' This is untrue. Chuck Norris can change the laws of physics. With his fists.",
        "Chuck Norris doesn't stub his toes. He accidentally destroys chairs, bedframes, and sidewalks.",
        "Using his trademark roundhouse kick, Chuck Norris once made a field goal in Tampa Bay Stadium from the 50 yard line of San Diego Stadium.",
        "Chuck Norris roundhouse kicks don't really kill people. They wipe out their entire existence from the space-time continuum.",
        "Chuck Norris does not own a stove, oven, or microwave because revenge is a dish best served cold.",
        "Tom Clancy has to pay royalties to Chuck Norris because 'The Sum of All Fears' is the name of Chuck Norris' autobiography.",
        "Chuck Norris can slam a revolving door.",
        "Chuck Norris built a better mousetrap, but the world was too frightened to beat a path to his door.",
        "The original draft of The Lord of the Rings featured Chuck Norris instead of Frodo Baggins. It was only 5 pages long, as Chuck roundhouse kicked Sauron halfway through the first chapter.",
        "Chuck Norris eats beef jerky and craps gunpowder. Then, he uses that gunpowder to make a bullet, which he uses to kill a cow and make more beef jerky. Some people refer to this as the 'Circle of Life.'",
        "If, by some incredible space-time paradox, Chuck Norris would ever fight himself, he'd win. Period.",
        "Science Fact: Roundhouse kicks are comprised primarily of an element called Chucktanium.",
        "Chuck Norris proved that we are alone in the universe. We weren't before his first space expedition.",
        "Superman once watched an episode of Walker, Texas Ranger. He then cried himself to sleep.",
        "Chuck Norris doesn't step on toes. Chuck Norris steps on necks.",
        "Chuck Norris does not style his hair. It lays perfectly in place out of sheer terror.",
        "There is no such thing as global warming. Chuck Norris was cold, so he turned the sun up.",
        "A study showed the leading causes of death in the United States are: #1 Heart disease, #2 Chuck Norris, and #3 Cancer.",
        "Chuck Norris did in fact, build Rome in a day.",
        "Along with his black belt, Chuck Norris often chooses to wear brown shoes. No one has DARED call him on it. Ever.",
        "Once you go Norris, you are physically unable to go back.",
        "Ninjas want to grow up to be just like Chuck Norris. But usually they grow up just to be killed by Chuck Norris.",
        "Chuck Norris once sued Burger King after they refused to put razor wire in his Whopper Jr, insisting that that actually is 'his' way.",
        "The last thing you hear before Chuck Norris gives you a roundhouse kick? No one knows because dead men tell no tales.",
        "Chuck Norris is the only person in the world that can actually text a roundhouse kick.",
        "Wo hu cang long. The translation from Mandarin Chinese reads: 'Crouching Chuck, Hidden Norris'",
        "Chuck Norris can set ants on fire with a magnifying glass. At night.",
        "Some kids play Kick the can. Chuck Norris played Kick the keg.",
        "'Icy-Hot' is too weak for Chuck Norris. After a workout, Chuck Norris rubs his muscles down with liquid-hot lava.",
        "Chuck Norris cannot love, he can only not kill.",
        "When Chuck Norris was a baby, he didn't get his mother's milk. His mother served him whiskey, straight out of the bottle.",
        "According to Einstein's theory of relativity, Chuck Norris can actually roundhouse kick you yesterday.",
        "Chuck Norris once pulled out a single hair from his beard and skewered three men through the heart with it.",
        "In an act of great philanthropy, Chuck made a generous donation to the American Cancer Society. He donated 6,000 dead bodies for scientific research.",
        "Chuck Norris' favorite cut of meat is the roundhouse.",
        "Chuck Norris recently had the idea to sell his urine as a canned beverage. We now know this beverage to be Red Bull.",
        "Chuck Norris invented a language that incorporates karate and roundhouse kicks. So next time Chuck Norris is beating you up, don’t be offended or hurt, he may be just trying to tell you he likes your hat.",
        "If at first you don't succeed, you're not Chuck Norris.",
        "If Chuck Norris were a calendar, every month would be named Chucktober, and every day you'd receive a roundhouse kick to the face.",
        "Fear is not the only emotion Chuck Norris can smell. He can also detect hope, as in: I hope I don't get a roundhouse kick from Chuck Norris.",
        "Behind every successful man, there is a woman. Behind every dead man, there is Chuck Norris.",
        "Chuck Norris brushes his teeth with a mixture of iron shavings, industrial paint remover, and wood-grain alcohol.",
        "The easiest way to determine Chuck Norris' age is to cut him in half and count the rings.",
        "There is endless debate about the existence of the human soul. Well it does exist and Chuck Norris finds it delicious.",
        "The USA did not boycott the 1980 Summer Olympics in Moscow due to political reasons: Chuck Norris killed the entire US team with a single roundhouse kick during TaeKwonDo practice.",
        "Do you know why Baskin Robbins only has 31 flavors? Because Chuck Norris doesn't like Fudge Ripple.",
        "Chuck Norris was what Willis was talkin' about.",
        "Google won't search for Chuck Norris because it knows you don't find Chuck Norris, he finds you.",
        "Chuck Norris can lead a horse to water AND make it drink.",
        "Nagasaki never had a bomb dropped on it. Chuck Norris jumped out of a plane and punched the ground.",
        "It is scientifically impossible for Chuck Norris to have had a mortal father. The most popular theory is that he went back in time and fathered himself.",
        "Chuck Norris destroyed the periodic table, because Chuck Norris only recognizes the element of surprise.",
        "It is believed dinosaurs are extinct due to a giant meteor. That's true if you want to call Chuck Norris a giant meteor.",
        "Chuck Norris shot the sheriff, but he roundhouse kicked the deputy.",
        "That's not Chuck Norris doing push-ups... that's Chuck Norris moving the Earth away from the path of a deadly asteroid.",
        "Chuck Norris can judge a book by its cover.",
        "How many Chuck Norris' does it take to change a light bulb? None, Chuck Norris prefers to kill in the dark.",
        "As President Roosevelt said: 'We have nothing to fear but fear itself. And Chuck Norris.'",
        "Chuck Norris just says 'no' to drugs. If he said 'yes', it would be to collapse Colombia's Drug Lord infrastructure.",
        "Since 1940, the year Chuck Norris was born, roundhouse kick related deaths have increased 13,000 percent.",
        "Chuck Norris does not own a house. He walks into random houses and people move.",
        "It is better to give than to receive. This is especially true of a Chuck Norris roundhouse kick.",
        "Chuck Norris is the only person to ever win a staring contest against Ray Charles and Stevie Wonder.",
        "Industrial logging isn't the cause of deforestation. Chuck Norris needs toothpicks.",
        "Chuck Norris smells what the Rock is cooking... because the Rock is Chuck Norris' personal chef.",
        "When Chuck Norris plays Oregon Trail, his family does not die from cholera or dysentery, but rather, roundhouse kicks to the face.",
        "Chuck Norris is the reason why Waldo is hiding.",
        "Chuck Norris does not eat. Food understands that the only safe haven from Chuck Norris' fists is inside his own body.",
        "Chuck Norris built a time machine and went back in time to stop the JFK assassination. As Oswald shot, Chuck met all three bullets with his beard, deflecting them. JFK's head exploded out of sheer amazement.",
        "Chuck Norris uses a night light. Not because Chuck Norris is afraid of the dark, but the dark is afraid of Chuck Norris.",
        "When Bruce Banner gets mad, he turns into the Hulk. When the Hulk gets mad, he turns into Chuck Norris.",
        "Chuck Norris kills anyone that asks: 'Do you want fries with that?'. Because by now everyone should know that Chuck doesn't want fries with anything. Ever.",
        "Chuck Norris once kicked a horse in the chin. Its decendants are known today as Giraffes.",
        "Sticks and stones may break your bones, but a Chuck Norris glare will liquefy your kidneys.",
        "Human cloning is outlawed because of Chuck Norris, because then it would be possible for a Chuck Norris roundhouse kick to meet another Chuck Norris roundhouse kick. Physicists theorize that this contact would end the universe.",
        "Chuck Norris once went skydiving, but promised never to do it again. One Grand Canyon is enough.",
        "Chuck Norris's version of a 'chocolate milkshake' is a raw porterhouse wrapped around ten Hershey bars, and doused in diesel fuel.",
        "In a fight between Batman and Darth Vader, the winner would be Chuck Norris.",
        "Chuck Norris puts his pants on one leg at a time, just like the rest of us. The only difference is, then he kills people.",
        "Contrary to popular belief, the Titanic didn't hit an iceberg. The ship was off course and ran into Chuck Norris while he was doing the backstroke across the Atlantic.",
        "Chuck Norris can win at solitaire with only 18 cards.",
        "Maslow's theory of higher needs does not apply to Chuck Norris. He only has two needs: killing people and finding people to kill.",
        "The truth will set you free. Unless Chuck Norris has you, in which case, forget it buddy!",
        "Kryptonite has been found to contain trace elements of Chuck Norris roundhouse kicks to the face. This is why it is so deadly to Superman.",
        "Coroners refer to dead people as the ABC's. Already Been Chucked.",
        "Chuck Norris doesn't look both ways before he crosses the street... he just roundhouses any cars that get too close.",
        "Chuck Norris does not have to answer the phone. His beard picks up the incoming electrical impulses and translates them into audible sound.",
        "When the boogeyman goes to sleep every night he checks his closet for Chuck Norris.",
        "How many roundhouse kicks does it take to get to the center of a tootsie pop? Just one. From Chuck Norris.",
        "Chuck Norris was born on May 6, 1945. Nazi Germany surrendered May 7, 1945. Coincidence? I think not.",
        "Chuck Norris doesnt wear a watch, HE decides what time it is.",
        "There used to be a street named after Chuck Norris, but it was changed because nobody crosses Chuck Norris and lives.",
        "Chuck Norris has already been to Mars. That's why there are no signs of life.",
        "Chuck Norris and Superman once fought each other on a bet. The loser had to start wearing his underwear on the outside of his pants.",
        "Some magicans can walk on water, Chuck Norris can swim through land.",
        "Chuck Norris counted to infinity. Twice.",
        "Fear of spiders is aracnaphobia, fear of tight spaces is chlaustraphobia, fear of Chuck Norris is called Logic.",
        "Death once had a near-Chuck Norris experience.",
        "Chuck Norris once urinated in a semi truck's gas tank as a joke... that truck is now known as Optimus Prime.",
        "Chuck Norris once got bit by a rattle snake. After three days of pain and agony... the rattle snake died.",
        "Chuck Norris can cut through a hot knife with butter.",
        "There is no theory of evolution. Just a list of animals Chuck Norris allows to live.",
        "Chuck Norris made a Happy Meal cry.",
        "Chuck Norris doesn't use Facebook, Twitter, or Instagram... he's already following you.",
        "Chuck Norris can hear sign language.",
        "Every time Chuck Norris looks into a mirror it breaks. Even glass is not stupid enough to get between Chuck Norris and Chuck Norris.",
        "Chuck Norris has an Xbox Live account. On Playstation.",
        "Chuck Norris donates blood to NASA for rocket fuel.",
        "When Chuck Norris was born, the only person who cried was the doctor. Never slap Chuck Norris.",
        "When Chuck Norris crosses the street, cars look both ways for Chuck Norris.",
        "Chuck Norris is so persuasive that he convinced a mirror he wasn't there.",
        "Chuck Norris once killed 37 terrorists with only 2 bullets... the first bullet was a warning shot.",
        "Chuck Norris flew his first paper airplane when he was 4 years old. It landed yesterday.",
        "When Chuck Norris was asked if he believed that the world was going to end in 2016 he resonded: 'Depends how I'm feeling that day.'",
        "Chuck Norris once bowled a perfect game... with a golf ball.",
        "The phrase 'break a leg' was originally coined by Chuck Norris's co-stars in Walker, Texas Ranger as a good luck charm, indicating that a broken leg might be the worst extent of their injuries. This never proved to be the case.",
        "Chuck Norris only uses stunt doubles for crying scenes.",
        "Some kids pee their name in snow. Chuck Norris pees his name in concrete.",
        "Dana White has never offered Chuck Norris a UFC contract out of concern for the well being of his fighters.",
        "Chuck Norris' hands are protected under the 2nd Amendment.",
        "Trains stop at Chuck Norris crossings.",
        "Chuck Norris can knit the softest sweater using electrical pylons.",
        "Chuck Norris's GPS never tells him to turn around.",
        "When Chuck Norris throws a boomerang, it doesn't come back.",
        "Chuck Norris can send a text message using a rotary phone.",
        "Chuck Norris makes Spock cry.",
        "Chuck Norris audits the IRS.",
        "When Chuck Norris lost his first tooth, the tooth fairy put it under her pillow.",
        "Chuck Norris' dog is a Velociraptor.",
        "Chuck Norris threw a grenade and killed 50 people, then it exploded.",
        "Chuck Norris once broke a mirror over the head of a black cat while standing under a ladder on Friday the thirteenth. The next day he won the lottery.",
        "Chuck Norris can speak French... in Russian.",
        "Chuck Norris can put out a fire with a gallon of gasoline.",
        "Chuck Norris once climbed Mt. Everest in 15 minutes, 14 of which he was building a snowman at the bottom.",
        "A bulletproof vest wears Chuck Norris for protection.",
        "Chuck Norris doesn't dial the wrong number, you pick up the wrong phone.",
        "Every Chuck Norris joke is a five star joke just because it says Chuck Norris.",
        "Chuck Norris can kill your imaginary friends.",
        "Chuck Norris beat the sun in a staring contest.",
        "Chuck Norris was once charged with three attempted murders in Boulder County, but the Judge quickly dropped the charges because Chuck Norris does not 'attempt' murder.",
        "When Chuck Norris gives you the finger, he's telling you how many seconds you have left to live.",
        "When Chuck Norris was in middle school, his English teacher assigned an essay: 'What is courage?' He received an A+ for turning in a blank page with only his name at the top.",
        "When Chuck Norris does division, there are no remainders.",
        "Chuck Norris' calendar goes straight from March 31st to April 2nd. No one fools Chuck Norris.",
        "When a zombie apocalypse starts, Chuck Norris doesn't try to survive. The zombies do.",
        "When Chuck Norris was born he drove his mom home from the hospital.",
        "If he wanted to, Chuck Norris could rob a bank. By phone.",
        "Big foot claims he saw Chuck Norris.",
        "The real reason Hitler killed himself is because he found out that Chuck Norris is Jewish.",
        "Chuck Norris once went to mars. That's why there are no signs of life.",
        "Chuck Norris can hit you so hard your blood will bleed.",
        "The reason the Holy Grail has never been recovered is because nobody is brave enough to ask Chuck Norris to give up his favourite coffee mug.",
        "Chuck Norris CAN find the end of a circle.",
        "Chuck Norris doesn't play 'hide-and-seek.' He plays 'hide-and-pray-I-don't-find-you.'",
        "Chuck Norris is the only person that can punch a cyclops between the eye.",
        "Brett Favre can throw a football over 50 yards. Chuck Norris can throw Brett Favre even further.",
        "It is considered a great accomplishment to go down Niagara Falls in a wooden barrel. Chuck Norris can go up Niagara Falls in a cardboard box.",
        "Chuck Norris can drown a fish.",
        "M.C. Hammer learned the hard way that Chuck Norris can touch this.",
        "If you spell Chuck Norris wrong on Google it doesn't say, 'Did you mean Chuck Norris?' It simply replies, 'Run while you still have the chance.'",
        "Leading hand sanitizers claim they can kill 99.9 percent of germs. Chuck Norris can kill 100 percent of whatever the hell he wants.",
        "Chuck Norris' tears cure cancer. Too bad he has never cried.",
        "Chuck Norris doesn't have good aim. His bullets just know better than to miss.",
        "Chuck Norris has a diary. It's called the Guinness Book of World Records.",
        "Chuck Norris beat Halo 1, 2, 3, 4, and 5 on Legendary with a broken Guitar Hero controller.",
        "Chuck Norris tells Simon what to do.",
        "Chuck Norris knows Victoria's secret.",
        "Chuck Norris's Blood Type is AK-47.",
        "The saddest moment for a child is not when he learns Santa Claus isn't real, it's when he learns Chuck Norris is.",
        "The reason newborn babies cry is because they know they have just entered a world with Chuck Norris.",
        "Bill Gates lives in constant fear that Chuck Norris' PC will crash.",
        "Chuck refers to himself in the fourth person.",
        "Chuck actually died four years ago, but the Grim Reaper can't get up the courage to tell him.",
        "Chuck Norris does not submit to homeland security, he IS homeland security.",
        "Chuck Norris's computer has no 'backspace' button, Chuck Norris doesn't make mistakes.",
        "Jack was nimble, Jack was quick, but Jack still couldn't dodge Chuck Norris' roundhouse kick.",
        "Chuck Norris is the only person on the planet that can kick you in the back of the face.",
        "On a high school math test, Chuck Norris put down 'Violence' as every one of the answers. He got an A+ on the test because Chuck Norris solves all his problems with Violence.",
        "Chuck Norris can unscramble an egg.",
        "If you rearrange the letters in 'Chuck Norris', they also spell 'Crush Rock In'. The words 'with his fists' are understood.",
        "The original title for Star Wars was 'Skywalker: Texas Ranger'. Starring Chuck Norris.",
        "Guantuanamo Bay, Cuba, is the military code-word for Chuck Norris' basement.",
        "Chuck Norris' roundhouse kick is so powerful, it can be seen from outer space by the naked eye.",
        "Ozzy Osbourne bites the heads off of bats. Chuck Norris bites the heads off of Siberian Tigers.",
        "He who lives by the sword, dies by the sword. He who lives by Chuck Norris, dies by the roundhouse kick.",
        "The phrase 'dead ringer' refers to someone who sits behind Chuck Norris in a movie theater and forgets to turn their cell phone off.",
        "Staring at Chuck Norris for extended periods of time without proper eye protection will cause blindess, and possibly foot sized brusies on the face.",
        "Chuck Norris can taste lies.",
        "One time, Chuck Norris accidentally stubbed his toe. It destroyed the entire state of Ohio.",
        "Chuck Norris can blow bubbles with beef jerky.",
        "Chuck Norris does, in fact, live in a roundhouse.",
        "4 out of 5 doctors fail to recommend Chuck Norris as a solution to most problems. Also, 80% of doctors die unexplained, needlessly brutal deaths.",
        "The only sure things are Death and Taxes and when Chuck Norris goes to work for the IRS, they'll be the same thing.",
        "Chuck Norris' first job was as a paperboy. There were no survivors.",
        "The square root of Chuck Norris is pain. Do not try to square Chuck Norris, the result is death.",
        "To be or not to be? That is the question. The answer? Chuck Norris.",
        "Chuck Norris has never been in a fight, ever. Do you call one roundhouse kick to the face a fight?",
        "There are two types of people in the world... people that suck, and Chuck Norris.",
        "Chuck Norris never wet his bed as a child. The bed wet itself out of fear.",
        "If you were somehow able to land a punch on Chuck Norris your entire arm would shatter upon impact. This is only in theory, since, come on, who in their right mind would try this?",
        "Jean-Claude Van Damme once kicked Chuck Norris. He was then awakened from his dream by a roundhouse kick to the face.",
        "MacGyver immediately tried to make a bomb out of some Q-Tips and Gatorade, but Chuck Norris roundhouse kicked him in the solar plexus. MacGyver promptly threw up his own heart.",
        "Jack Bauer tried to use his detailed knowledge of torture techniques, but to no avail: Chuck Norris thrives on pain. Chuck Norris then ripped off Jack Bauer's arm and beat him to death with it. Game, set, match.",
        "Chuck Norris eats steak for every single meal. Most times he forgets to kill the cow.",
        "The First Law of Thermodynamics states that energy can neither be created nor destroyed... unless it meets Chuck Norris.",
        "Chuck Norris doesn't go on the internet, he has every internet site stored in his memory. He refreshes webpages by blinking.",
        "It is said that looking into Chuck Norris' eyes will reveal your future. Unfortunately, everybody's future is always the same: death by a roundhouse kick to the face.",
        "Chuck Norris knows everything there is to know... except for the definition of mercy.",
        "Scientifically speaking, it is impossible to charge Chuck Norris with 'obstruction of justice.' This is because even Chuck Norris cannot be in two places at the same time.",
        "Chuck Norris never has to wax his skis because they're always slick with blood.",
        "When you say 'no one's perfect', Chuck Norris takes this as a personal insult.",
        "Chuck Norris can win a game of Trivial Pursuit with one roll of the dice, and without answering a single question... just a nod of the head, and a stroke of the beard.",
        "182,000 Americans die from Chuck Norris-related accidents every year.",
        "Paper beats rock, rock beats scissors, and scissors beats paper, but Chuck Norris beats all 3 at the same time.",
        "All roads lead to Chuck Norris. And by the transitive property, a roundhouse kick to the face.",
        "Chuck Norris never goes to the dentist because his teeth are unbreakable. His enemies never go to the dentist because they have no teeth.",
        "Chuck Norris was once in a knife fight, and the knife lost.",
        "If you work in an office with Chuck Norris, don't ask him for a three-hole-punch.",
        "The First rule of Chuck Norris is: you do not talk about Chuck Norris.",
        "When Chuck Norris plays Monopoly, it affects the actual world economy.",
        "Chuck Norris can be unlocked on the hardest level of Tekken. But only Chuck Norris is skilled enough to unlock himself. Then he roundhouse kicks the Playstation back to Japan.",
        "Chuck Norris drinks napalm to quell his heartburn.",
        "Every time someone uses the word 'intense', Chuck Norris always replies 'you know what else is intense?' followed by a roundhouse kick to the face.",
        "As an infant, Chuck Norris' parents gave him a toy hammer. He gave the world Stonehenge.",
        "Chuck Norris once ordered a steak in a restaurant. The steak did what it was told.",
        "There are only two things that can cut diamonds: other diamonds, and Chuck Norris.",
        "Chuck Norris was banned from competitive bull riding after a 1992 exhibition in San Antonio, when he rode the bull 1,346 miles from Texas to Milwaukee Wisconsin to pick up his dry cleaning.",
        "Chuck Norris uses Sriracha instead of Visine.",
        "The chemical formula for the highly toxic cyanide ion is CN-. These are also Chuck Norris' initials. This is not a coincidence.",
        "A man once claimed Chuck Norris knocked him out twice by a roundhouse kick in the face, but it was promptly dismissed as false... no one could survive it the first time.",
        "Chuck Norris sleeps with a pillow under his gun.",
        "Chuck Norris doesn't chew gum. Chuck Norris chews tin foil.",
        "Aliens DO indeed exist. They just know better than to visit a planet that Chuck Norris is on.",
        "Every time Chuck Norris smiles, someone dies. Unless he smiles while he's roundhouse kicking someone in the face. Then two people die.",
        "Some people ask for a Kleenex when they sneeze, Chuck Norris asks for a body bag.",
        "A man once asked Chuck Norris if his real name is 'Charles'. Chuck Norris did not respond, he simply stared at him until he exploded.",
        "Chuck Norris starts everyday with a protein shake made from Carnation Instant Breakfast, one dozen eggs, pure Colombian cocaine, and rattlesnake venom. He injects it directly into his neck with a syringe.",
        "Chuck Norris doesn't see dead people. He makes people dead.",
        "Chuck Norris is the only person who can simultaneously hold and fire FIVE Uzis: One in each hand, one in each foot -- and the 5th one he roundhouse kicks into the air, so that it sprays bullets.",
        "For undercover police work, Chuck Norris pins his badge underneath his shirt, directly into his chest.",
        "We live in an expanding universe. All of it is trying to get away from Chuck Norris.",
        "Do you know the 11th Commandment? Thou shalt not piss off Chuck Norris. This commandment is rarely enforced, as it is impossible to accomplish.",
        "Chuck Norris is his own line at the DMV.",
        "Two wrongs don't make a right. Unless you're Chuck Norris. Then two wrongs make a roundhouse kick to the face.",
        "Who let the dogs out? Chuck Norris let the dogs out... and then roundhouse kicked them in the face.",
        "Chuck Norris can do a roundhouse kick faster than the speed of light. This means that if you turn on a light switch, you will be dead before the lightbulb turns on.",
        "Chuck Norris has never won an Academy Award for acting... because he's not acting.",
        "If Chuck Norris wants your opinion, he'll beat it into you.",
        "Not everyone that Chuck Norris is mad at gets killed. Some get away. They are called astronauts.",
        "Chuck Norris has to register every part of his body as a separate lethal weapon. His spleen is considered a concealed weapon in over 50 states.",
        "A movie scene depicting Chuck Norris losing a fight with Bruce Lee was the product of history's most expensive visual effect. When adjusted for inflation, the effect cost more than the Gross National Product of Paraguay.",
        "Godzilla is a Japanese rendition of Chuck Norris' first visit to Tokyo.",
        "Chuck Norris once rode a nine foot grizzly bear through an automatic car wash, instead of taking a shower.",
        "'Sweating bullets' is literally what happens when Chuck Norris gets too hot.",
        "After taking a steroids test doctors informed Chuck Norris that he had tested positive. He laughed upon receiving this information, and said 'of course my urine tested positive, what do you think they make steroids from?'",
        "Chuck Norris doesn't daydream. He's too busy giving other people nightmares.",
        "When Arnold says 'I'll be back' in Terminator movie it is implied that he's going to ask Chuck Norris for help.",
        "There are no such things as tornados. Chuck Norris just hates trailer parks.",
        "Chuck Norris does not follow fashion trends, they follow him. But then he turns around and roundhouse kicks their face in. So nobody follows Chuck Norris.",
        "Chuck Norris once participated in the running of the bulls. He walked.",
        "The Manhattan Project was not intended to create nuclear weapons, it was meant to recreate the destructive power in a Chuck Norris Roundhouse Kick. They didn't even come close.",
        "Chuck Norris has banned rainbows from the state of North Dakota.",
        "Chuck Norris runs on batteries. Specifically, Die Hards.",
        "Chuck Norris will never have a heart attack. His heart isn't nearly foolish enough to attack him.",
        "Only Chuck Norris can prevent forest fires.",
        "Chuck Norris is not Irish. His hair is soaked in the blood of his victims.",
        "They say curiosity killed the cat. This is false. Chuck Norris killed the cat. Every single one of them.",
        "Chuck Norris doesn't say 'who's your daddy', because he knows the answer.",
        "Chuck Norris originally wrote the first dictionary. The definition for each word is as follows - A swift roundhouse kick to the face.",
        "Love does not hurt. Chuck Norris does.",
        "Chuck Norris once roundhouse kicked a salesman. Over the phone.",
        "The pen is mightier than the sword, but only if the pen is held by Chuck Norris.",
        "Chuck Norris knows the last digit of pi.",
        "Those aren't credits that roll after Walker Texas Ranger. It is actually a list of fatalities that occurred during the making of the episode.",
        "The air around Chuck Norris is always a balmy 78 degrees.",
        "Chuck Norris plays racquetball with a waffle iron and a bowling ball.",
        "Count from one to ten. That's how long it would take Chuck Norris to kill you... fourty seven times.",
        "The 1972 Miami Dolphins lost one game, it was a game vs. Chuck Norris and three seven year old girls. Chuck Norris won with a roundhouse kick to the face in overtime.",
        "Chuck Norris is not Politically Correct. He is just Correct. Always.",
        "Mr. T pities the fool. Chuck Norris rips the fool's head off.",
        "Chuck Norris had to stop washing his clothes in the ocean. The tsunamis were killing people.",
        "A man once taunted Chuck Norris with a bag of Lay's potato chips, saying 'Betcha can't eat just one!' Chuck Norris proceeded to eat the chips, the bag, and the man in one deft move.",
        "In the first Jurassic Park movie, the Tyrannosaurus Rex wasn't chasing the jeep. Chuck Norris was chasing the Tyrannosaurus AND the jeep.",
        "Rules of fighting: #1 Don't bring a knife to a gun fight. #2 Don't bring a gun to a Chuck Norris fight.",
        "Chuck Norris is the only man who has, literally, beaten the odds. With his fists.",
        "When you play Monopoly with Chuck Norris, you do not pass go, and you do not collect two hundred dollars. You will be lucky if you make it out alive.",
        "Chuck Norris likes his ice like he likes his skulls: crushed.",
        "Chuck Norris does all of his grocery shopping at Home Depot.",
        "Chuck Norris doesn't have disk latency because the hard drive knows to hurry the hell up.",
        "Chuck Norris can't test for equality because he has no equal.",
        "Chuck Norris can delete the Recycling Bin.",
        "Chuck Norris's beard can type 140 wpm.",
        "Chuck Norris's keyboard doesn't have a Ctrl key because nothing controls Chuck Norris.",
        "When Chuck Norris is surfing the web he gets the message 'Warning: Google Chrome has deemed this user to be malicious or dangerous. Proceed?'.",
        "Chuck Norris doesn't need a debugger, he just stares down the bug until the code confesses.",
        "Chuck Norris' Internet connection is faster upstream than downstream because even data has more incentive to run from him than to him.",
        "If Chuck Norris writes code with bugs, the bugs fix themselves.",
        "No one has ever pair-programmed with Chuck Norris and lived to tell about it.",
        "No one has ever spoken during review of Chuck Norris' code and lived to tell about it.",
        "Chuck Norris finished World of Warcraft.",
        "Chuck Norris does infinit loops in 4 seconds.",
        "Chuck Norris killed two stones with one bird.",
        "Chuck Norris can speak Braille.",
        "Chuck Norris can install a 64 bit OS on 32 bit machines.",
        "Chuck Norris doesn't need an account. He just logs in.",
        "Code runs faster when Chuck Norris watches it.",
        "Chuck Norris doesn’t win, he allows you to lose.",
        "Chuck Norris told the Most Interesting Man in the World that he can only drink Dos Equis.",
        "There is no chin under Chuck Norris’ beard… just another fist.",
        "Tornados occur when Chuck Norris sneezes.",
        "Chuck Norris can understand women.",
        "Sharks have a Chuck Norris week.",
        "Chuck Norris can speak Russian in Chinese.",
        "Chuck Norris once sold eBay to eBay on eBay.",
        /*"Chuck Norris’s dog pick’s up his own sh*t because Chuck Norris doesn't take sh*t from anyone.",*/
        "Chuck Norris can sneeze with his eyes open.",
        "When Alexander Bell invented the telephone he had 3 missed calls from Chuck Norris.",
        "Chuck Norris counted to infinity. Twice.",
        "Chuck Norris doesn't flush the toilet, he scares the crap out of it.",
        "Chuck Norris gives the sun cancer.",
        "Chuck Norris can light a fire by rubbing two ice-cubes together.",
        "Chuck Norris makes onions cry.",
        "Chuck Norris won 'America's Got Talent' using sign language.",
        "Chuck Norris can strangle you with a cordless phone.",
        "Alcohol has a Chuck Norris problem.",
        "If you flipped over China it says made by Chuck Norris.",
        "What is Chuck Norris' favorite color? Red of course.",
        "A meteor did not kill the dinosaurs, Chuck Norris just went on a hunting trip.",
        "Chuck Norris doesn't fall, he attracts the earth to him.",
        "Chuck Norris can download the whole internet onto a floppy disk."
    ]
    
    func getRandomJoke() -> String {
        let randomGenerator = GKRandomSource.sharedRandom().nextIntWithUpperBound(chuckJokes.count)
        
        return chuckJokes[randomGenerator]
    }
}